name: Docker Image CI
 
on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Docker login
      env: 
        DOCKER_USER: ${{secret.DOCKER_USER}}
        DOCKER_PASSWORD: ${{secret.DOCKER_PASSWORD}}
      run: |
        docker login -u $DOCKER_USER -p $DOCKER_PASSWORD |
    - name: Docker login
        docker build -f haproxy/haproxy.yaml . --tag haproxy:$(date +%s) |
    - name: Docker push to Docker_HUB
      run: docker push ${{secret.DOCKER_USER}}/test_1:haproxy
      
